# Example configuration for custom CLI agent
agent:
  provider: cli
  command: "amp"         # Replace with your CLI tool
  cli_args: []          # Optional command-line arguments
  timeout: 10m          # Maximum time for each operation
  retries: 3            # Number of retry attempts
  rate_limit: 2s        # Delay between retries

# Logging configuration
logging:
  level: info
  format: text